include $(TOPDIR)/rules.mk

LUCI_TITLE:=BACnet MS/TP Configuration
LUCI_DEPENDS:=+luci-base +bacnet-stack
LUCI_PKGARCH:=all

PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
