#!/bin/sh

# Create bacnet config if not exists
if [ ! -e "/etc/config/bacnet" ]; then
	touch /etc/config/bacnet

	# general section
	uci set bacnet.general=service
	uci set bacnet.general.enabled='0'

	# mstp section
	uci set bacnet.mstp=mstp
	uci set bacnet.mstp.device='RS485-1'
	uci set bacnet.mstp.baudrate='38400'
	uci set bacnet.mstp.mac_address='1'
	uci set bacnet.mstp.max_master='127'
	uci set bacnet.mstp.max_info_frames='1'

	# device section
	uci set bacnet.device=device
	uci set bacnet.device.device_instance='1234'
	uci set bacnet.device.device_name='SenseCAP Gateway'
	uci set bacnet.device.vendor_name='Seeed'
	uci set bacnet.device.model_name='reComputer R1225'

	uci commit bacnet
fi

exit 0
