#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set bacnet.gateway=gateway
	set bacnet.gateway.enabled='0'
	set bacnet.gateway.device_name='SenseCAP Gateway'
	set bacnet.gateway.device_id='8000'
	set bacnet.gateway.local_endpoint='0.0.0.0'
	set bacnet.gateway.port='47808'
	set bacnet.gateway.whitelist='0'
	set bacnet.gateway.default_profiles='Senso8-LRS10701 Senso8-LRS20100 Senso8-LRS20200 Senso8-LRS20310 Senso8-LRS20600 Senso8-LRS20LD0 Senso8-LRS20Uxx Senso8-LRS2M001'
	set bacnet.mqtt=mqtt
	set bacnet.mqtt.enabled='0'
	set bacnet.mqtt.host=''
	set bacnet.mqtt.port='1883'
	set bacnet.mqtt.mqtt_version='3.1.1'
	set bacnet.mqtt.qos='1'
	set bacnet.mqtt.keepalive='10'
	set bacnet.mqtt.clean_session='1'
	set bacnet.mqtt.retain='0'
	set bacnet.mqtt.client_id=''
	set bacnet.mqtt.enable_auth='0'
	set bacnet.mqtt.ssl_mode='none'
	set bacnet.mqtt.uplink_topic='application/BACNet/device/{{device_EUI}}/rx'
	set bacnet.mqtt.downlink_topic='application/BACNet/device/{{device_EUI}}/tx'
	set bacnet.mqtt.downlink_ack_topic='application/BACNet/device/{{device_EUI}}/ack'
	commit bacnet
EOF

# Create profile directory
mkdir -p /etc/bacnet/profiles

exit 0
